config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :entries, param: :slug do
      resources :external_links, only: [:create, :destroy]    
  end

  get 'search', to: "entries#results"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :entries
    belongs_to :collection
    
    validates :name, presence: true
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :categories, -> { order 'name asc' }
    has_many :entries, -> { order 'title asc' }, :through => :categories
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :category, optional: true
  has_many :external_links
  has_one :collection, :through => :category
  
  validates :title, presence: true, uniqueness: true, :case_sensitive => false
  validates :body, presence: true

  before_create :set_slug
  before_update :set_slug

  include Discard::Model
  default_scope -> { kept }

  include PgSearch
  pg_search_scope :search_title_or_body, 
    against: [:title, :body],
    using: {
      tsearch: { prefix: true }
    }

  def to_param
    slug
  end

  def set_slug
    self.slug = self.title.parameterize.truncate(80, omission: '')
  end

end

app/models/external_link.rb
class ExternalLink < ApplicationRecord
  belongs_to :entry
  
  validates :url, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # devise :database_authenticatable, :registerable,
  # :recoverable, :rememberable, :validatable

  # Make omniauthable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID   
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token

      # Also save email and image 
      user.email = auth.info.email
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # def new_session_path(scope)
    #     new_user_session_path
    # end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sidebar_props, only: [:show, :index, :new, :edit, :update, :create, :results]
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_category_options, only: [:new, :edit, :update, :create]

  def index
    @recently_changed = Entry.order("updated_at DESC").limit(4)
  end

  def results
    @results = Entry.search_title_or_body(params["search_query"])
    @search_query = params["search_query"]
  end


  def show
    @link = ExternalLink.new
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)
    @entry[:last_editor] = current_user.name
    if @entry.save
      redirect_to @entry, notice: 'Entry successfully created.'
    else
      render :new
    end
  end

  def update
    @entry.update(entry_params)
    @entry[:last_editor] = current_user.name
    if @entry.save
      redirect_to @entry, notice: 'Entry successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @entry.discard
    redirect_to entries_path
  end

  private

  def set_sidebar_props
    @collections = Collection.order("name ASC").includes(:categories, :entries).as_json(include: {
      categories: {
        include: :entries
      }
    })
  end

  def set_entry
    @entry = Entry.find_by( slug: params[:slug])
    @collectionId = @entry.collection.id
  end

  def set_category_options
    @collection_category_options = Collection.all.map do |col|
        [col.name, col.categories.map { |c| [c.name, c.id] }]
      end
  end

  def entry_params
    params.require(:entry).permit(:title, :body, :category_id)
  end

end

app/controllers/external_links_controller.rb
class ExternalLinksController < ApplicationController
    before_action :set_entry, only: [:create, :destroy]
    before_action :set_external_link, only: [:destroy]

    def create
      @link = @entry.external_links.build(link_params)
      if @link.save
        redirect_to @entry, notice: 'Link successfully created.'
      else
        redirect_to @entry, alert: 'There was a problem.'
      end
    end

    def destroy
      @link.destroy
      redirect_to @entry, notice: "Link successfully removed"
    end

    private

    def set_entry
        @entry = Entry.find_by slug: params[:entry_slug]
    end

    def set_external_link
        @link = @entry.external_links.find(params[:id])
    end

    def link_params
        params.require(:external_link).permit(:description, :url)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def google_oauth2
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
        else
            session["devise.google_data"] = request.env["omniauth.auth"]
        end

        redirect_to '/'
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_contents.html.erb
<aside class="contents">

  <button id="toggle-contents" class="contents__toggle">
    <h2 class="contents__toggle-title">See contents</h2>
    <%= image_tag "chevron.svg", class: "contents__toggle-icon" %>
  </button>

  <ul class="contents__list">
    <% @categories.each do |cat| %>
      <% if cat.entries.any? %>
        <li>
          <h3 class="contents__heading"><%= cat.name %></h3>
          <ul class="contents__category-list">
            <% cat.entries.each do |entry| %>
              <li class="contents__entry"><%= link_to entry.title, entry_path(entry), class: "contents__entry-link #{"contents__entry-link--active" if current_page? entry_path(entry)}" %></li>
            <% end %>
          </ul>
        </li>
      <% end %>
      
    <% end %>
  </ul>

</aside>

app/views/entries/_form.html.erb
<%= form_with model: @entry, local: true do |f| %>

    <% if @entry.errors.any? %>
        <div class="notification notification--error">
            <p>Errors prevented this entry from being saved:</p>
            <ul>
                <% @entry.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-field">
        <%= f.label :title, class: "form-label" %>
        <%= f.text_field :title, class: "form-input form-input--title", required: true, placeholder: "Add title..." %>
    </div>

    <div class="form-field">
        <%= f.label :category_id, class: "form-label" %>
        <%= f.select :category_id, grouped_options_for_select( @collection_category_options , @entry.category_id), {}, { :class => "form-select"} %>
    </div>

    <div class="form-field">
        <%= f.label :body, class: "form-label visually-hidden" %>
        <trix-editor input="entry_body" class="form-input form-input--body" placeholder="Start writing your entry..." ></trix-editor>
        <%= f.hidden_field :body, class: "form-input" %>
    </div>

    <%= f.submit "Save entry", class: "button" %>

<% end %>

app/views/entries/edit.html.erb
<% content_for :title, "Editing entry" %>
<%= render layout: 'layouts/app' do %>

    <div class="editor" >
        <h1 class="visually-hidden">Editing entry</h1>
        <%= link_to "← Go back", entry_path(@entry), class: "go-back" %>
        <div class="editor__header"></div>

        <%= render 'entries/form' %>
        
        <section class="editor__delete">
            <p>Or, remove this entry entirely:</p>
            <%= link_to fa_icon( "trash", text: "Remove"), entry_path(@entry), method: :delete, data: {confirm: "Are you sure you want to remove this entry?"}, class: "button button--danger" %> 
        </section>
        
    </div>

<% end %>

app/views/entries/index.html.erb
<%= render layout: 'layouts/app' do %>

    <div class="entry">
        <div class="entry__header">
            <h1 class="entry__title">FutureGov Tech Wiki</h1>
        </div>

        <div class="entry__grid">
            <section class="entry__content">
                <p>A tool for FutureGov’ers to document, share and more easily access our combined knowledge of technology & data.<br/><br/>

                Initially we’ve filled this with brief explanations of common terms and concepts but anybody at FG can add to, or edit the content. It’s an experiment for now so we’d suggest keeping your content reasonably short and linking off to other resources for more detail (Google Docs etc).<br/><br/>

                We're running some analytics to help us understand how people use the tool but <strong>please add any specific feedback or feature requests/ideas to the Trello board linked in the footer</strong> (or slack/chat with Stuart or Jaye)<br/><br/>

                <p><em>Wiki-Wiki-Wild-Wild Tech</em></p>
                <p>x x x</p>
                <p>🤖✊❤</p>
            </section>

            <section class="links">
                <h2 class="links__title">Recent changes</h2>
                <ul class="links__list">

                    <% @recently_changed.each do |change| %>
                        <li class="links__link-container">
                            <%= link_to entry_path(change), class: "links__link" do %>
                                <p class="links__link-description"><%= change.title %></p>
                                <p class="links__link-url"><%= time_ago_in_words(change.updated_at) %> ago</p>
                            <% end %>
                        </li>
                    <% end %>

                </ul>
            </section>


        </div>
    </div>
<% end %>

app/views/entries/new.html.erb
<% content_for :title, "New entry" %>
<%= render layout: 'layouts/app' do %>
    <div class="editor" >
        <h1 class="visually-hidden">New entry</h1>

        <%= render 'entries/form' %>
    </div>
<% end %>

app/views/entries/results.html.erb
<%= render layout: 'layouts/app' do %>

    <section class="search-results">
        <h2 class="search-results__number"><%= @results.count %> <% if @results.count == 1 %>result<% else %>results<% end %></h2>
        <ul class="search-results__results">
        <% @results.each do |result| %>
            <li class="search-results__result">
                <%= link_to entry_path(result) do %>
                    <h3 class="search-results__title"><%= result.title %></h3>
                <% end %>
                <p class="search-results__body"><%= strip_tags result.body.truncate(140) %></p>
            </li>
        <% end %>
        </ul>
    </section>

<% end %>

app/views/entries/show.html.erb
<% content_for :title, @entry.title %>
<%= render layout: 'layouts/app' do %>
    <div class="entry">
        <section class="entry__header">
            <h1 class="entry__title"><%= @entry.title %></h1>
            <div class="entry__meta">
                <p class="entry__updated">Last updated <%= time_ago_in_words(@entry.updated_at) %> ago <% if @entry.last_editor %>by <%= @entry.last_editor %><% end %></p>
                <%= link_to fa_icon( "edit", text: "Edit entry"), edit_entry_path(@entry), class: "entry__edit-link" %>
            </div>
        </section>

        <div class="entry__grid">
            <section class="entry__content">
                <%= sanitize @entry.body %>
            </section>
            <%= render 'links/links' %>
        </div>
    </div>
<% end %>

app/views/layouts/_app.html.erb
<div class="app">
    <%# <div class="app-body"> %>
    
        <%= react_component "Sidebar", {
          logoUrl: asset_url("wordmark.svg"),
          collections: @collections,
          currentSlug: params[:slug],
          currentCollectionId: @collectionId,
        }, class: "sidebar-container", prerender: true %>

        <div class="main-pane">
            <%= render 'layouts/header' %>

            <main class="content-area">
              <% if notice %>
                <p class="notification notification--notice"><%= fa_icon "check" %> <%= notice %></p>
              <% end %>
              <% if alert %>
                <p class="notification notification--alert"><%= fa_icon "exclamation" %> <%= alert %></p>
              <% end %>

              <%= yield %>
            </main>

            <%= render 'layouts/footer' %>
        </div>

    <%# </div> %>
</div>

app/views/layouts/_entries.html.erb
<div class="app">
    <%= render 'layouts/header' %>
    <div class="app-body">
        <%= render 'layouts/contents' %>
        <div class="main-pane">
            <main class="content-area">

              <% if notice %>
                <p class="notification notification--notice"><%= fa_icon "check" %> <%= notice %></p>
              <% end %>
              <% if alert %>
                <p class="notification notification--alert"><%= fa_icon "exclamation" %> <%= alert %></p>
              <% end %>

              <%= yield %>

            </main>
            <%= render 'layouts/footer' %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
    <p class="site-footer__info">Built and maintained by the FutureGov technology and data practice.</p>
    <a class="site-footer__link" href="https://trello.com/b/KSJAaZQ4/technology-wiki-feedback-ideas" target="blank">Give feedback</a>
    <a class="site-footer__link" href="https://github.com/wearefuturegov/futuregov-technology" target="blank">View on Github</a>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "site-footer__link" %>
</footer>

app/views/layouts/_ga.html.erb
<% if Rails.env == 'production' %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137584195-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%= Rails.application.credentials[:ga_tracking_id] %>');
    </script>
<% end %>

app/views/layouts/_header.html.erb
<header class="site-header">

  <div class="site-header__top-row">
    <%= link_to root_path, class: "site-header__mobile-masthead" do %>
      <%= image_tag "brandmark.svg", class: "site-header__mobile-logo" %>
      <h1 class="site-header__mobile-name">Tech</h1>
    <% end %>

    <%= link_to new_entry_path, class: "site-header__mobile-action" do %>
      <span class="site-header__icon">+</span> New entry
    <% end %>
  </div>

  <div class="site-header__bottom-row">

    <%= render 'layouts/search' %>

    <div class="site-header__actions">
      <%= link_to new_entry_path, class: "site-header__action site-header__action--primary" do %>
        <span class="site-header__icon">+</span> New entry
      <% end %>
      <% if current_user %>
        <%= link_to('Log out', destroy_user_session_path, method: :delete, class: "site-header__action") %>   
      <% end %>
    </div>

  </div>

</header>

app/views/layouts/_search.html.erb
<%= form_tag "/search", class: "search-form", method: :get do %>

    <div class="search-field">
        <%= label_tag "search_query", "Search query", class: "visually-hidden" %>
        <%= text_field_tag "search_query", @search_query, placeholder: "Search", class: "search-field__input", required: true %>
        <%= button_tag(type: 'submit', class: "search-field__icon") do %>
            <%= fa_icon("search") %>
            <span class="visually-hidden">Search</span>
        <% end %>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>



    <title><%= content_for?(:title) ? yield(:title) + " | " : "" %>FutureGov Technology</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type => "image/x-icon" %>
    <link rel="stylesheet" href="https://use.typekit.net/uru8mtl.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="viewport" content="width=device-width">
    <%= render 'layouts/ga'%>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_links.html.erb
<section class="links">
    <h2 class="links__title">Learn more</h2>
    <ul class="links__list">

        <% if @entry.external_links.any? %>
            <% @entry.external_links.each do |link| %>
                <li class="links__link-container">
                    <%= link_to link.url, target: :_blank, class: "links__link" do %>
                        <p class="links__link-description"><%= link.description %></p>
                        <p class="links__link-url"><%= truncate(link.url, length: 35) %></p>
                        <%= link_to fa_icon( "trash"), entry_external_link_path(@entry, link), method: :delete, data: {confirm: "Are you sure you want to remove this link?"}, class: "links__remove-link" %> 
                    <% end %>
                </li>
            <% end %>
        <% end %>

        <li class="links__link-container" aria-live="polite">
            <%= form_with model: [@entry, @link], local: true do |f| %>
                <%= react_component "NewLink", {link: @link}, prerender: true %>
            <% end %>
        </li>
    </ul>
</section>